# ================================================
# Configuration Apache — GLPI UNFPA Togo
# ================================================

<VirtualHost *:80>
    ServerName glpi.unfpa-togo.local
    DocumentRoot /var/www/html/glpi/public

    <Directory /var/www/html/glpi/public>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
        Header always set X-Content-Type-Options nosniff
        Header always set X-Frame-Options SAMEORIGIN
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/glpi_error.log
    CustomLog ${APACHE_LOG_DIR}/glpi_access.log combined
</VirtualHost>